spring.application.name=demo
server.port=8000
# database location
spring.datasource.url=jdbc:mysql://localhost:3306/school_sys
# MYSQL username
spring.datasource.username=root
# MYSQL password
spring.datasource.password=carlosmaina2006
# Automatically creates/update tables
    # 1. create option destroys previous schemas and data and adds new ones when application is started, this is used only during development
    # 2. create-drop option creates a schema and destroys it when application is stopped
    # 3. none option disables DDL(Data Defination Language)
    # 4. update option creates schema if it is not there updates schema if there are changes made
    # 5. 
spring.jpa.hibernate.ddl-auto=create
# show sql queries in the console
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true
